# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('expires', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='UsictAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_timestamp', models.DateTimeField()),
                ('duration_of_class', models.IntegerField()),
                ('attendance', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'usict_attendance',
            },
        ),
        migrations.CreateModel(
            name='UsictBatchAllocation',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
            options={
                'db_table': 'usict_batch_allocation',
            },
        ),
        migrations.CreateModel(
            name='UsictStudents',
            fields=[
                ('enrollment_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_admission', models.IntegerField()),
                ('password', models.CharField(max_length=600)),
                ('course', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('batch_id', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictBatchAllocation')),
            ],
            options={
                'db_table': 'usict_students',
            },
        ),
        migrations.CreateModel(
            name='UsictSubjectAllocation',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('type_of_subject', models.CharField(db_column='type', max_length=15)),
                ('batch_id', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictBatchAllocation')),
            ],
            options={
                'db_table': 'usict_subject_allocation',
            },
        ),
        migrations.CreateModel(
            name='UsictTeacher',
            fields=[
                ('instructor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usict_teacher',
            },
        ),
        migrations.AddField(
            model_name='usictsubjectallocation',
            name='instructor_code',
            field=models.ForeignKey(db_column='instructor_code', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictTeacher'),
        ),
        migrations.AddField(
            model_name='usictattendance',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictStudents'),
        ),
        migrations.AddField(
            model_name='usictattendance',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictSubjectAllocation'),
        ),
        migrations.AlterUniqueTogether(
            name='usictattendance',
            unique_together=set([('subject_id', 'lecture_timestamp', 'student')]),
        ),
    ]
