# Generated by Django 2.0.1 on 2018-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0002_usictteacher_isdean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usictsubjectallocation',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
