# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0003_auto_20180120_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usictstudents',
            name='batch_id',
            field=models.IntegerField(blank=True, db_column='batch_id', null=True, verbose_name='UsictBatchAllocation'),
        ),
        migrations.AlterField(
            model_name='usictsubjectallocation',
            name='batch_id',
            field=models.IntegerField(db_column='batch_id', verbose_name='UsictBatchAllocation'),
        ),
    ]
