# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0004_auto_20180130_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usictattendance',
            name='student',
            field=models.IntegerField(db_column='student', verbose_name='UsictStudents'),
        ),
    ]
