# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0005_auto_20180130_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usictattendance',
            name='student',
            field=models.CharField(db_column='student', max_length=100, verbose_name='UsictStudents'),
        ),
    ]
