# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0006_auto_20180130_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usictattendance',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictStudents'),
        ),
        migrations.AlterField(
            model_name='usictstudents',
            name='batch_id',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictBatchAllocation'),
        ),
        migrations.AlterField(
            model_name='usictsubjectallocation',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='deandashboard.UsictBatchAllocation'),
        ),
    ]
