# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deandashboard', '0010_auto_20180130_0356'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usictstudents',
            table='usict_students',
        ),
    ]
